<<<<<<< HEAD
title: Interactive Wall
description: This is the documentation for the interactive wall I am designing
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
=======
title: Minimal theme
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
>>>>>>> aa7b35d684a1e8490737eddcf12b26a1c027829a
