title: Interactive Wall
description: This is the documentation for the interactive wall I am designing
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal


sections: [
    ['week8', 'Week 8'],
    ['week9', 'Week 9'],
    ['week10', 'Week 10'],
    ['week11', 'Week 11'],
]


imageurl: "https:harryiliffe.githubpages.io/interactive-wall/images/"
